# Generated by Django 3.2.12 on 2022-02-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='newsletter_subscription',
        ),
    ]
