# Generated by Django 3.2.12 on 2022-02-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_newsletter_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
