# Generated by Django 3.2.12 on 2022-04-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rating.rating')),
                ('body', models.TextField(verbose_name='réponse')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='a répondu le')),
            ],
        ),
    ]
